{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'matlab'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-70-2f970a1e89be>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mmatlab\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mengine\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0meng\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmatlab\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mengine\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstart_matlab\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'loading'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mdotMatFile\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/quickloader.mat'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'matlab'"
     ]
    }
   ],
   "source": [
    "import matlab.engine\n",
    "eng = matlab.engine.start_matlab()\n",
    "\n",
    "print('loading')\n",
    "dotMatFile = '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/quickloader.mat'\n",
    "\n",
    "eng.load(dotMatFile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loading\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'expt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '01f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '03c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '08d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '0Qe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '0R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '0pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '0vf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '13c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '16f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '18d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '1Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '1R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '1pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '1qe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '23c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '26f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '28d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '2Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '2R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '2pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '33c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '36f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '38d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '3Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '3R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '3pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '43c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '46f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '48d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '4Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '4R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '4pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '53c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '56f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '58d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '5Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '5R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '5pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '63c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '66f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '68d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '6Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '6R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '6pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '73c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '76f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '78d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '7Jb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '7Qe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '7R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '7pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '83c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '86f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '88d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '8Qe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '8R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '8Re'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '8pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '91f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '93c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '98d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '9Qe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '9R'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node '9pe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Agc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'At'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Bgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Bt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Bvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Cgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Ct'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Cvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'DKb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Dgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Dt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Dvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Et'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Evd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Ft'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Fvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'G4f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Gt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Gvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'H9d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Ht'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Hvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Iif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'It'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Ivd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Jif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Jt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Jvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Kif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Kt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Kvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Lif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Lt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Lvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Mif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Mt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Mvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'N3f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Nif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Nt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Nvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Oif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Ot'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Ovd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Pif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Pt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Pvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Qif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Qvd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'RJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Rif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'SJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Sif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'TJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Tif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'U2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'UJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'UR'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Uif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'V8d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'VJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'VR'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'VS'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Vif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Vwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'W8d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'WJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'WKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'WR'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Wif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Wob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'X3c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'X8d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'XJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'XR'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Xif'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Y3c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Y4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Y6f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Y8d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'YJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'YR'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Z3c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Z6f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Z8d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ZJb'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ZR'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'Zpe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'a2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'a4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'a9d'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'aBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'aRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'aS'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ahc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'aob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'aqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'awf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'b'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'b2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'b4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'b6f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bCc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bS'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'bwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'c2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'c4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'cBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'cRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'cS'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'cob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'cqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'cwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'd2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'd4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'dBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'dRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'dS'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'dob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'dqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'dwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'e2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'e4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'eBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'eRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'eS'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'eob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'eqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ewf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'f2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'f4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'fBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'fRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'fob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'fqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'fwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'g2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'g4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'gBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'gRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'gob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'gqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'gwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'h2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'h4c'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'hBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'hRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'hob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'hqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'hwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'i2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'iBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'iRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'iob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'iqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'iwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'j2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'jBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'jRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'job'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'jqe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'jwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'k2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'kBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'kRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'kob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'kwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'l2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'lBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'lRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'lob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'lwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'm2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'mBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'mRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'mob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'mwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'n2f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'nBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'nRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'nob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'nwd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'nwf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'oBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'oRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ogc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'oob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'owf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'pBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'pKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'pRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'pgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'pob'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'qBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'qKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'qRe'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'qgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'rBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'rKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'rgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'sBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'sKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'sgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 't5f'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'tBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'tKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'tgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'uBc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'uKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ugc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ujf'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'vKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'vgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'vt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'wKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'wgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'wt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'wu'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'xKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'xgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'xt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'yKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'ygc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'yt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'zKd'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'zgc'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'zt'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'annot'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'session1'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'session2'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'session3'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'mean'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'peak'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'post'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n",
      "/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/tables/attributeset.py:298: DataTypeWarning: Unsupported type for attribute 'MATLAB_fields' in node 'rast'. Offending HDF5 class: 9\n",
      "  value = self._g_getattr(self._v_node, name)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.io.pytables.HDFStore'>\n",
      "File path: /home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/quickloader.mat\n",
      "Empty\n",
      "finished\n"
     ]
    }
   ],
   "source": [
    "import h5py\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "print('loading')\n",
    "dotMatFile = '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/quickloader.mat'\n",
    "\n",
    "store = pd.HDFStore(dotMatFile)\n",
    "#df = store.select('session1')\n",
    "#df \n",
    "print(store)\n",
    "print('finished')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loading\n",
      "Keys: [<HDF5 dataset \"means\": shape (7, 1), type \"|O\">, <HDF5 dataset \"means_matched\": shape (7, 1), type \"|O\">, <HDF5 dataset \"resps\": shape (7, 1), type \"|O\">, <HDF5 dataset \"session1\": shape (7, 1), type \"|O\">, <HDF5 dataset \"session2\": shape (7, 1), type \"|O\">, <HDF5 dataset \"session3\": shape (7, 1), type \"|O\">]\n",
      "finished loading\n"
     ]
    }
   ],
   "source": [
    "import h5py\n",
    "import numpy as np\n",
    "\n",
    "print('loading')\n",
    "dotMatFile = '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/quickloader.mat'\n",
    "\n",
    "with h5py.File(dotMatFile, 'r') as f: # read only\n",
    "    \n",
    "    \n",
    "    print(\"Keys: %s\" % list(f['expt'].values()))\n",
    "    \n",
    "print('finished loading')\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<HDF5 file \"quickloader.mat\" (mode r+)>\n"
     ]
    }
   ],
   "source": [
    "print(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
